/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-10-18 15:29:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1679745626898L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1679751214062L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    <!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <!-- Required meta tags -->\r\n");
      out.write("    <meta charset=\"utf-8\" />\r\n");
      out.write("    <meta\r\n");
      out.write("      name=\"viewport\"\r\n");
      out.write("      content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("      integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\"\r\n");
      out.write("      crossorigin=\"anonymous\" />\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/extra-css.css\"/>\r\n");
      out.write("    <title>Hello, world!</title>\r\n");
      out.write("    \r\n");
      out.write("  </head>\r\n");
      out.write("  <!-- col-sm- -->\r\n");
      out.write("  <body>\r\n");
      out.write("  <div class=\"wapper\">\r\n");
      out.write("    <header class=\"p-3\">\r\n");
      out.write("        <div class=\"container flex-column d-flex flex-md-row\">\r\n");
      out.write("        <div class=\"header_logo text-center\">\r\n");
      out.write("          <a href=\"#\">\r\n");
      out.write("          <h2>\r\n");
      out.write("            PRJ321x\r\n");
      out.write("          </h2>\r\n");
      out.write("\r\n");
      out.write("            Welcome\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"header_form  mt-3 mt-md-0 ml-md-5\">\r\n");
      out.write("          <div class=\"btn-group\" role=\"group\">\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-secondary dropdown-toggle\" data-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("              Category\r\n");
      out.write("            </button>\r\n");
      out.write("            <div class=\"dropdown-menu\">\r\n");
      out.write("              <a class=\"dropdown-item\" href=\"#\">Dropdown link</a>\r\n");
      out.write("              <a class=\"dropdown-item\" href=\"#\">Dropdown link</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"input-group\">\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" placeholder=\"Recipient's username\" aria-label=\"Recipient's username\" aria-describedby=\"button-addon2\">\r\n");
      out.write("            <div class=\"input-group-append\">\r\n");
      out.write("              <button  type=\"button\" class=\"btn btn-warning\">Search</button>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("        <nav class=\"d-flex align-items-center justify-content-around\">\r\n");
      out.write("          <ul class=\"header_nav d-flex\">\r\n");
      out.write("            <li class=\"header_nav--item\">\r\n");
      out.write("              Home\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"header_nav--item\">\r\n");
      out.write("              Product\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"header_nav--item\">\r\n");
      out.write("              About Us\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          <div class=\"header_auth d-flex\">\r\n");
      out.write("            <p class=\"header_auth_login\">\r\n");
      out.write("              Login\r\n");
      out.write("            </p>\r\n");
      out.write("            <p class=\"header_auth_register\">\r\n");
      out.write("              Register\r\n");
      out.write("            </p>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </header>");
      out.write("\r\n");
      out.write("<div class=\"row shadow\">\r\n");
      out.write("        <div class=\" bg-white col-6 text-center login\">\r\n");
      out.write("        <div>\r\n");
      out.write("            <h2>Sign in</h2>\r\n");
      out.write("            <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\" method=\"post\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                  <input  \r\n");
      out.write("                  required=\"required\" name=\"username\" type=\"text\" \r\n");
      out.write("                  class=\"form-control\" placeholder=\"Enter username\" id=\"username\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                  <input oninvalid=\"this.setCustomValidity()\" \r\n");
      out.write("                  required=\"required\" name=\"password\" type=\"password\" \r\n");
      out.write("                  class=\"form-control\" placeholder=\"Enter password\" id=\"pwd\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <p><a href=\"/login\">Forgot your password?</a></p>\r\n");
      out.write("                <button type=\"submit\" class=\"btn btn-success\">Login</button>\r\n");
      out.write("              </form>\r\n");
      out.write("              </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\" text-white col-6 text-center welcome \">\r\n");
      out.write("               <div>\r\n");
      out.write("            <h2>Welcome Back!</h2>\r\n");
      out.write("            <p>To keep connected with us please login with your personal info</p>\r\n");
      out.write("        </div>  \r\n");
      out.write("        </div>        \r\n");
      out.write("    </div>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
 String userID = request.getParameter("username"); 
      out.write("\r\n");
      out.write("   <footer class=\"mt-5\">\r\n");
      out.write("      <div class=\"footer_box\">\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"footer_contact\">\r\n");
      out.write("        <p>\r\n");
      out.write("          Lorem ipsum dolor sit amet consectetur adipisicing elit. </br> sit molestias quasi reprehenderit quaerat. Enim. Harum, illum iusto,\r\n");
      out.write("          voluptate\r\n");
      out.write("        </p>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    \r\n");
      out.write(" \r\n");
      out.write("    <!-- Optional JavaScript -->\r\n");
      out.write("    <!-- jQuery first, then Popper.js, then Bootstrap JS -->\r\n");
      out.write("    <script\r\n");
      out.write("      src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\"\r\n");
      out.write("      integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\"\r\n");
      out.write("      crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script\r\n");
      out.write("      src=\"https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js\"\r\n");
      out.write("      integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\"\r\n");
      out.write("      crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script\r\n");
      out.write("      src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js\"\r\n");
      out.write("      integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\"\r\n");
      out.write("      crossorigin=\"anonymous\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
